# Generated by Django 2.2.28 on 2025-07-31 21:04

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200724_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
