# Generated by Django 2.2.28 on 2025-08-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoin',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventUserWishList',
        ),
        migrations.DeleteModel(
            name='UserCoin',
        ),
    ]
